# Generated by Django 4.0 on 2025-11-17 03:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('price', models.IntegerField()),
                ('condition', models.CharField(choices=[('新品', '新品'), ('未使用に近い', '未使用に近い'), ('目立った傷や汚れなし', '目立った傷や汚れなし'), ('やや傷や汚れあり', 'やや傷や汚れあり'), ('傷や汚れあり', '傷や汚れあり')], max_length=50)),
                ('image', models.ImageField(blank=True, upload_to='products/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.customuser')),
            ],
        ),
    ]
