# Generated by Django 4.0 on 2025-11-17 04:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('author', models.CharField(blank=True, max_length=200)),
                ('category', models.CharField(choices=[('fiction', '文学・小説'), ('business', 'ビジネス・経済'), ('manga', 'マンガ'), ('lnovel', 'ライトノベル'), ('history', '歴史'), ('hobby', '趣味・実用'), ('study', '学習参考書'), ('other', 'その他')], max_length=50)),
                ('description', models.TextField(blank=True)),
                ('price', models.IntegerField()),
                ('image', models.ImageField(upload_to='books/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.customuser')),
            ],
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
